# Generated by Django 3.0.5 on 2020-05-24 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa:')),
                ('color', models.IntegerField(choices=[(1, 'black'), (2, 'white'), (3, 'antracyt'), (4, 'red'), (5, 'blue')], null=True, verbose_name='Kolor:')),
                ('description', models.TextField(verbose_name='Opis:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena:')),
                ('available', models.BooleanField(default=True, verbose_name='Dostępność:')),
                ('foto', models.ImageField(null=True, upload_to='klima_image', verbose_name='Zdjęcie:')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nazwisko')),
                ('mail', models.CharField(max_length=128, null=True, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=128, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Producent')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Podaj Imię:')),
                ('last_name', models.CharField(max_length=128, null=True, verbose_name='Nazwisko:')),
                ('mail', models.CharField(max_length=128, verbose_name='E-mail:')),
                ('phone', models.IntegerField(verbose_name='Telefon:')),
                ('topic', models.IntegerField(choices=[(0, '------'), (1, 'klimatyzacje'), (2, 'ozonowanie'), (3, 'pompy ciepła')], verbose_name='Temat:')),
                ('area', models.IntegerField(null=True, verbose_name='Metraż w m2:')),
                ('cubature', models.IntegerField(null=True, verbose_name='Kubatura w m3:')),
                ('bulding', models.IntegerField(choices=[(0, '-----'), (1, 'Dom jednorodzinny'), (2, 'Mieszkanie w bloku'), (3, 'Biuro'), (4, 'Hala magazynowa/produkcyjna')], null=True, verbose_name='Typ budynku:')),
                ('flor', models.IntegerField(choices=[(0, '-----'), (1, 'parter'), (2, '1 piętro'), (3, '2 piętro'), (4, '3 piętro'), (5, '4 piętro'), (6, '5 piętro'), (7, 'wysokie piętro - powyżej 5 pięra')], null=True, verbose_name='Ilość pięter:')),
                ('message', models.TextField(verbose_name='Uwagi:')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='klimaApp.AirProduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimaApp.AirProduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='klimaApp.OrderProduct', to='klimaApp.AirProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimaApp.AirProduct')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='klimaApp.CartProducts', to='klimaApp.AirProduct'),
        ),
        migrations.AddField(
            model_name='airproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Category', verbose_name='Kategoria:'),
        ),
        migrations.AddField(
            model_name='airproduct',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Producer', verbose_name='Producent:'),
        ),
    ]
