# Generated by Django 3.0.5 on 2020-04-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klimaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airproduct',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='products',
        ),
        migrations.AddField(
            model_name='airproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Category'),
        ),
        migrations.AddField(
            model_name='airproduct',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimaApp.Producer'),
        ),
        migrations.AlterField(
            model_name='airproduct',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='airproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Producent'),
        ),
    ]
