# Generated by Django 3.0.5 on 2020-04-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimaApp', '0002_auto_20200426_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='airproduct',
            name='color',
            field=models.IntegerField(choices=[(1, 'black'), (2, 'white'), (3, 'red'), (4, 'yellow'), (5, 'blue')], null=True),
        ),
    ]
