# Generated by Django 3.0.5 on 2020-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimaApp', '0003_airproduct_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airproduct',
            name='color',
            field=models.IntegerField(choices=[(1, 'black'), (2, 'white'), (3, 'antracyt'), (4, 'red'), (5, 'blue')], null=True),
        ),
    ]
