# Generated by Django 2.2.11 on 2020-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimaApp', '0005_auto_20200427_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='airproduct',
            name='foto',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
